CREATE TABLE cars_image
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id VARCHAR(36) NOT NULL,
    image_id VARCHAR(36) NOT NULL,

    CONSTRAINT car_images_car_id_fk FOREIGN KEY (car_id) REFERENCES cars (id),
    CONSTRAINT car_images_image_id_fk FOREIGN KEY (image_id) REFERENCES images (id),
    CONSTRAINT car_images_constraint_unique_key UNIQUE (id, car_id, image_id),
    CONSTRAINT image_unique_key UNIQUE (image_id)
);